package org.example.mockexam.enums;

public enum ReadingQuestionType {
    MULTIPLE_CHOICE,
    MATCHING_HEADINGS,
    MATCHING_INFORMATION,
    MATCHING_FEATURES,
    MATCHING_SENTENCE_ENDINGS,
    TRUE_FALSE_NOT_GIVEN,
    YES_NO_NOT_GIVEN,
    SENTENCE_COMPLETION,
    SUMMARY_COMPLETION,
    NOTE_TABLE_FLOWCHART_COMPLETION,
    DIAGRAM_LABEL_COMPLETION,
    SHORT_ANSWER_QUESTIONS
}
